### ISSUE TITLE
Got error when trying!

### ISSUE THREAD

**Issue by leminhtuan2015** [czarneckid/redis_pagination#7]
I were doing by following steps.
step1:  gem install redis_pagination
step 2: irb
step 3: require 'redis_pagination'   => true
step 4: 

``` ruby
 RedisPagination.configure do |configuration|
       configuration.redis = Redis.new(:db => 15)
     configuration.page_size = 25
  end
```

step 5: add_items_to_list('items', RedisPagination.page_size + 2)

=>>  NoMethodError: undefined method `add_items_to_list' for main:Object

Please give me some idea to resole my issue

**Comment by czarneckid** [comment]
Write a method called `add_items_to_list` that will add items to your list.
